module.exports = {
  STATE_UPDATE: 'state_update',
  CREATE_ROOM: 'create_room',
  ROOM_CREATED: 'room_created',
  ROOM_CLOSED: 'room_closed',
  JOIN_ROOM: 'join_room',
  START_GAME: 'start_game',
  SELECT_QUESTION: 'select_question',
  ASSIGN_DAILY_DOUBLE: 'assign_daily_double',
  REVEAL_QUESTION: 'reveal_question',
  UNLOCK_BUZZERS: 'unlock_buzzers',
  BUZZ: 'buzz',
  JUDGE_ANSWER: 'judge_answer',
  SUBMIT_WAGER: 'submit_wager',
  SUBMIT_FINAL_ANSWER: 'submit_final_answer',
};
